language: r
sudo: false
cache: packages


env:
  - LINTR_COMMENT_BOT=false

r_packages:
  - devtools
  - testit
  - ape
  - ade4
  - phytools
  - expm
  - pracma

r_github_packages:
  - jimhester/lintr
  - jimhester/covr
  - MangoTheCat/goodpractice

# Go into folder, from https://github.com/travis-ci/travis-ci/issues/5775#issuecomment-202411532
before_install:
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev
  - cd DAISIE

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'library(goodpractice); gp()'